In [1]:
import numpy as np

1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array

In [3]:
    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [4]:
list_temperature=np.array(list_temperature )

In [6]:
type(list_temperature)

numpy.ndarray

 <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>


In [7]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [8]:
weights=np.array(weights)

In [12]:
weights[weights>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)

In [15]:
np.random.randint(20,40,10)

array([31, 31, 32, 32, 23, 22, 29, 29, 20, 32])

In [17]:
np.random.seed(73)
np.random.randint(20,40,10)

array([38, 34, 30, 36, 28, 23, 21, 26, 30, 27])

	
4. Write a program to get the fifth power of the first five positive integers

In [18]:
array5=np.arange(1,6)

In [19]:
array5

array([1, 2, 3, 4, 5])

In [21]:
list(np.power(array5,5))

[1, 32, 243, 1024, 3125]

	
5. Write a program to create an array of all the odd integers from 50 to 100

In [28]:
aodd=np.arange(51,100,2)

In [29]:
aodd

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

Use the array given below: (or create your own array)

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [32]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arc=np.array(A)
arc

array([[ 1,  4,  8],
       [ 5,  7,  3],
       [ 9, 14,  2]])

In [33]:
np.sum(A,axis=0)

array([15, 25, 13])

7. Write a code to get the element-wise remainder of an array after division by 8

In [34]:
#Use the list given below:

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [35]:
ewr=np.remainder(num,8)

In [36]:
ewr

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array

In [41]:
d1=np.arange(1,21)

In [42]:
d1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
d2=d1.reshape(2,10)

In [44]:
d2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [49]:
d2[0,1:6]

array([2, 3, 4, 5, 6])

	
9. Write a program to find common values between two arrays

In [50]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

In [51]:
x=np.intersect1d(prices_monday,prices_tuesday )
x

array([10, 50])

11. Write a program to add a new column ([5,7]) at the last position in the array given below

In [60]:
array1 = [[[3, 4], [8, 2],[5, 9]]]

In [61]:
np.append(array1,[[[5,7]]],axis=1)

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

	
12. Write a code to print the identity matrix of order 5

In [63]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
a=np.zeros((5,5))

In [69]:
np.fill_diagonal(a,1)

In [70]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.eye(5,5,k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

13. Write a program to transpose a matrix

In [76]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [77]:
np.transpose(M)

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

In [80]:
m=np.array(M)

In [81]:
m.T

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

14. Write a program to combine the two arrays vertically

In [82]:
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]

In [84]:
np.vstack((A1,A2))

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

15. Write a code to combine the two arrays horizontally

In [85]:
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

In [86]:
np.hstack((A1,A2))

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

16. Write a code to divide the array into three sub-arrays containing equal number of rows

In [87]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [90]:
A=np.array(A)
np.vsplit(A,3)

[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

17. Write a program to divide the array into two sub-arrays containing equal number of columns

In [92]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [93]:
B=np.array(B)
np.hsplit(B,2)

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

18. Write a program to perform one-to-one mapping of the two lists

In [98]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]

In [100]:
for i in range(len(L1)):
    print(L1[i],L2[i])

45 21
67 52
56 64
71 10
54 49
62 74
56 26


In [101]:
list(zip(L1,L2))

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]

In [103]:
for i,j in zip(L1,L2):
    print(i,j)

45 21
67 52
56 64
71 10
54 49
62 74
56 26


19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array

In [104]:
numbers=np.array([6, 5, 3, 15])

In [106]:
def all(x):
    for i in x:
        print((2*i-1)/(i+5))
all(numbers)

1.0
0.9
0.625
1.45


20. Create an array of integers from 20 to 2 with a step of -2

In [108]:
ar20_2=np.arange(20,2,-2)

In [109]:
ar20_2

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

21. Find the minimum value along each of the rows

In [110]:
num_array = np.array([[110, 102, 183],
                 [140, 175, 106],
                 [170, 195, 117],
                 [192, 140, 195]])

In [113]:
np.amin(num_array,axis=1)

array([102, 106, 117, 140])

22. Replace all odd numbers in the array with -2

In [114]:
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [115]:
for i in range(0,len(num_array)):
    if num_array[i]%2!=0:
        num_array[i]=-2
print(num_array)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


23. Remove all the elements from num_array1 that are present in num_array2

In [117]:
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([5,6,7,8,9])

In [118]:
new=[]
for i in num_array1:
    if i not in num_array2:
        new.append(i)
print(new)

[1, 2, 3, 4]


In [119]:
np.setdiff1d(num_array1,num_array2)

array([1, 2, 3, 4])

8. Get the positions where elements of two arrays match

In [120]:
num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])
num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(num_array1 == num_array2)

(array([1, 3, 5, 7], dtype=int64),)

9. Reverse each of the rows of the 2D array

In [121]:
num_array4 = np.arange(16).reshape(4,4)
print(num_array4)
print(np.fliplr(num_array4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


10. Swap row 1 and row 2 in the given array

In [124]:
num_array1 = np.arange(9).reshape(3,3)
num_array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
num_array1[[0,1]]==num_array1[[1,0]]

array([[False, False, False],
       [False, False, False]])

In [129]:
print(num_array1)

[[3 4 5]
 [0 1 2]
 [6 7 8]]
